#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil
#+TITLE: An Introduction to Mechanisms
#+AUTHOR: Marc Scott updated by C Delport and P Dougall

#+BEGIN_HTML
<div class="github-fork-ribbon-wrapper left">
        <div class="github-fork-ribbon">
            <a href="https://github.com/stcd11/7-SC-Mechanisms">Fork me on GitHub</a>
        </div>
    </div>
    <div class="github-fork-ribbon-wrapper right-bottom">
        <div class="github-fork-ribbon">
            <a href="../index.html">Back to Index</a>
        </div>
    </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
   
      <li><a href="assessment.html">Assessment</a></li>
    </ul>
  </div>
#+END_HTML

* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Homework Tasks
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
i) Find two examples for each of the three classes of lever.
 
ii) Label at least one example for each to show where the fulcrum/pivot, effort and load are.

*Upload your work to www.bournetolearn.com badge 1.*

** Calculate It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

- Calculate the answers to the following problems involving gear ratios:

1. A driver pulley has a diameter of 200mm and rotates with a speed of 30rpm. Calculate the speed of a driven pulley with a diameter of 100mm.
2. A driver pulley has a diameter of 80mm and rotates with a speed of 50rpm. Calculate the speed of a driven pulley with a diameter of 100mm.
3. A driver pulley has a diameter of 50mm and rotates with a speed of 10rpm. Calculate the required diameter of a driven pulley if we want it to rotate at 50rpm.

*Upload your answers to www.bournetolearn.com badge 2.*
